AllCops:
  NewCops: enable
  Exclude:
    - 'test/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'app/helpers/*'
    - 'config/spring.rb'
    - 'config/puma.rb'
    - 'Gemfile'
    - 'app/jobs/*'
    - 'db/migrate/*'
    - 'config/environments/production.rb'
    - 'config/initializers/devise.rb'
    - 'vender/**/*'

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false

# 文字列のfreezeをチェックしない
Style/FrozenStringLiteralComment:
  Enabled: false

# namespace付きのクラスの記載方法(::)許可
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 40

# 1行あたりの長さ
Layout/LineLength:
  Max: 160

# メソッドの長さ
Metrics/MethodLength:
  Max: 20

Lint/UnusedMethodArgument:
  Enabled:
    - 'app/controllers/application_controller.rb'

# スコープ内の無駄なローカル変数の割り当てチェック
Lint/UselessAssignment:
  Enabled:
    - 'app/controllers/application_controller.rb'

# 条件式と同時に変数代入
Lint/AssignmentInCondition:
  Enabled:
    - 'app/controllers/application_controller.rb'